name: Publish the website

on:
  push:
    branches:
      - test-site

jobs:
  publish:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checking out Calcite repository
        uses: actions/checkout@v1
      - name: Build site assets
        working-directory: site
        run: docker-compose run -e JEKYLL_UID=$(id -u) -e JEKYLL_GID=$(id -g) build-site
      - name: Deploy site to calcite-site repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: site
        run: |
          shopt -s extglob
          git config --global user.email "builds@apache.org"
          git config --global user.name "Calcite Automated Website Build"
          git config --global url."https://github:${GITHUB_TOKEN}@github.com/".insteadOf "https://github.com/"
          git clone --depth 1 --branch asf-site https://github.com/apache/calcite-site deploy
          cd deploy/
          rm -rf !(apidocs|avatica|testapidocs)
          cp -r ../target/* .
          git add .
          git commit -m "Automatic site deployment from Calcite at $GITHUB_SHA"
          git push origin HEAD:asf-site
